apiVersion: v1
kind: Service
metadata:
  name: nyashdev-qr-cafe-frontend-service
  namespace: nyashdev
spec:
  selector:
    project: nyashdev-qr-cafe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyashdev-qr-cafe-ingress
  namespace: nyashdev
spec:
  ingressClassName: nginx
  rules:
    - host: "nyashdev.stk8s.66bit.ru"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nyashdev-qr-cafe-frontend-service
                port:
                  number: 80
